local darken = require("oceanic-next.utils").darken
local editor = {}

function editor.highlights()
  local c = require("oceanic-next.config").colors
  return {
    Bold = { bold = true },
    Debug = { fg = c.red },
    Directory = { fg = c.blue },
    ErrorMsg = { fg = c.red, bg = c.base00 },
    Exception = { fg = c.red },
    FoldColumn = { fg = c.blue, bg = c.base00 },
    Folded = { fg = c.base03, bg = c.base01, italic = true },
    IncSearch = { fg = c.base01, bg = c.orange },
    Italic = { italic = true },

    Macro = { fg = c.red },
    MatchParen = { fg = c.base05, bg = c.base03 },
    ModeMsg = { fg = c.green },
    MoreMsg = { fg = c.green },
    Question = { fg = c.blue },
    Search = { fg = c.base03, bg = c.yellow },
    SpecialKey = { fg = c.base03 },
    TooLong = { fg = c.red },
    Underlined = { fg = c.red },
    Visual = { bg = c.base02 },
    VisualNOS = { fg = c.red },
    WarningMsg = { fg = c.red },
    WildMenu = { fg = c.base07, bg = c.blue },
    Title = { fg = c.blue },
    Conceal = { fg = c.blue },
    Cursor = { bg = c.base05 },
    NonText = { fg = c.base03 },
    Normal = { fg = c.base07, bg = c.base00 },

    NormalFloat = { fg = c.base07, bg = c.base00 },
    FloatBorder = { fg = c.base01, bg = c.base00 },
    FloatTitle = { fg = c.base00, bg = c.cyan },

    -- EndOfBuffer = { fg = c.base05, bg = c.base00 },
    LineNr = { fg = c.base03 }, --, bg = c.base00 },
    SignColumn = { fg = c.base00, bg = c.base00 },
    StatusLine = { fg = c.base07, bg = c.base00 },
    StatusLineNC = { fg = c.base07, bg = c.base00 },
    VertSplit = { fg = c.base01, bg = c.base00 },
    WinSeparator = { fg = c.base01, bg = c.base00 },
    ColorColumn = { bg = c.base01 },
    CursorColumn = { bg = c.base01 },
    CursorLine = { bg = c.base02 },
    CursorLineNr = { fg = c.base07 }, --, bg = c.base00 },
    PMenu = { fg = c.base04, bg = c.base01 },
    PMenuSel = { fg = c.base07, bg = c.blue },
    PmenuSbar = { bg = c.base02 },
    PmenuThumb = { bg = c.base07 },

    TabLine = { fg = c.base03, bg = darken(c.base00, 5) },
    TabLineFill = { fg = c.base03, bg = darken(c.base00, 5) },
    TabLineSel = { fg = c.base07, bg = c.base00, italic = false },

    helpExample = { fg = c.yellow },
    helpCommand = { fg = c.yellow },

    Boolean = { fg = c.orange },
    Character = { fg = c.red },
    Comment = { fg = c.base03, italic = true },
    Conditional = { fg = c.purple },
    Constant = { fg = c.orange },
    Define = { fg = c.purple },
    Delimiter = { fg = c.brown },
    Float = { fg = c.orange },
    Function = { fg = c.blue },

    Identifier = { fg = c.cyan, italic = true },
    Include = { fg = c.purple },
    Keyword = { fg = c.purple, italic = true },

    Label = { fg = c.yellow },
    Number = { fg = c.orange },
    Operator = { fg = c.orange },
    PreProc = { fg = c.yellow },
    Repeat = { fg = c.yellow },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.brown },
    Statement = { fg = c.red },
    StorageClass = { fg = c.yellow, italic = true },
    String = { fg = c.green },
    Structure = { fg = c.yellow },
    Tag = { fg = c.yellow },
    Todo = { fg = c.yellow, bg = c.base01 },
    Type = { fg = c.purple, italic = true },
    Typedef = { fg = c.purple, italic = true },

    SpellBad = { undercurl = true },
    SpellLocal = { undercurl = true },
    SpellCap = { undercurl = true },
    SpellRare = { undercurl = true },

    IndentBlanklineChar = { fg = c.base01, nocombine = true },
    IndentBlanklineSpaceChar = { fg = c.base01, nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = c.base01, nocombine = true },
    IblIndent = { fg = c.base01, nocombine = true },
    IblWhitespace = { fg = c.base01, nocombine = true },

    DiffAdd = { fg = c.green, bg = c.base00 },
    DiffChange = { fg = c.yellow, bg = c.base00 },
    DiffDelete = { fg = c.red, bg = c.base00 },
    DiffText = { fg = c.blue, bg = c.base00 },
    DiffAdded = { fg = c.green, bg = c.base00 },
    DiffFile = { fg = c.red, bg = c.base00 },
    DiffNewFile = { fg = c.green, bg = c.base00 },
    DiffLine = { fg = c.blue, bg = c.base00 },
    DiffRemoved = { fg = c.red, bg = c.base00 },
  }
end
return editor
